<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="dell" name="RetryFailedTestCases" tests="6" failures="1" timestamp="2 Apr 2018 07:46:45 GMT" time="0.087" errors="0">
  <testcase name="test1" time="0.023" classname="Tests.MyTests">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.002" classname="Tests.MyTests">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.002" classname="Tests.MyTests">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.002" classname="Tests.MyTests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at Tests.MyTests.test1(MyTests.java:12)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.002" classname="Tests.MyTests"/>
  <testcase name="test3" time="0.002" classname="Tests.MyTests"/>
</testsuite> <!-- RetryFailedTestCases -->
